version: '3'
services:
  webapp:
    image: streamlitcontainerregistry.azurecr.io/portfolio-app:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
        - "80:8501" 
        # second port is the container port which is listening at 8501
        # host port is the first port

