apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolioapp-deployment
  labels:
    app: streamlit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit
  template: # blueprint for pods. config of pods within deployment
    metadata:
      labels:
        app: streamlit
    spec:
      containers: # docker container
      - name: portfolio-webapp
        image: aaabdulkadir/portfolio-webapp
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: portfoliowebapp-service
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30000